In [1]:
import pandas as pd
import numpy as np 
import datasets

/u/camilleh/.conda/envs/jupyterlab-debugger/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
jigsaw_train = pd.read_csv('value/data/GLUE/SST/train.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'value/data/GLUE/SST/train.csv'

In [3]:
jigsaw_test = pd.read_csv('value/data/GLUE/SST/test.csv')

In [4]:
jigsaw_test['sentence'] = jigsaw_test['sentence'].astype('str')

In [5]:
jigsaw_train['sentence'] = jigsaw_train['sentence'].astype('str')

In [6]:
jigsaw_test

            id                                           sentence
0      7097320  [ Integrity means that you pay your debts.]\n\...
1      7097321  This is malfeasance by the Administrator and t...
2      7097322  @Rmiller101 - Spoken like a true elitist. But ...
3      7097323  Paul: Thank you for your kind words.  I do, in...
4      7097324  Sorry you missed high school. Eisenhower sent ...
...        ...                                                ...
97315  7194635  He should lose his job for promoting mis-infor...
97316  7194636  "Thinning project is meant to lower fire dange...
97317  7194637  I hope you millennials are happy that you put ...
97318  7194638  I'm thinking Kellyanne Conway (a.k.a. The Trum...
97319  7194639  I still can't figure why a pizza in AK cost mo...

[97320 rows x 2 columns]

In [7]:

jigsaw_train[jigsaw_train['sentence'].str.contains('\[')]

,id,target,sentence,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
211,239948,0.000000,"Hi Jeff, you bring up interesting points.\n\n""...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,26568,approved,0,0,0,1,0,0.0,0,4
299,240322,0.000000,I wonder how one can post an actual image? Mar...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,32846,approved,0,0,0,1,0,0.0,4,6
363,240417,0.000000,[Here's a relevant quote.](https://lh5.googleu...,0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,1,0,0.0,0,4
388,240447,0.000000,"Well, the easter egg in the penultimate senten...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,0,0,0.0,0,4
415,240485,0.000000,"While I agree with your conclusion, I think yo...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,0,0,0.0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1804501,6333342,0.000000,""" we're divided over issues, but people are di...",0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,399264,approved,0,0,0,0,0,0.0,10,4
1804710,6333658,0.000000,Falwell Jr. predicted that Moore would be vind...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,399518,approved,0,0,0,0,0,0.0,4,4
1804753,6333721,0.833333,I saved where I could because my children matt...,0.0,0.0,0.0,0.833333,0.0,NaN,NaN,...,399301,approved,0,0,0,0,0,0.0,0,6
1804868,6333965,0.000000,"cont....GBA: ""here's the summation of that ""l...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,399318,approved,0,0,0,0,0,0.0,0,4
1804873,6334010,0.000000,Students defined as EBD are legally just as di...,0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,399318,approved,0,0,0,0,0,0.0,0,4

In [8]:
jigsaw_train[jigsaw_train['sentence'].str.contains('\[')]

,id,target,sentence,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
211,239948,0.000000,"Hi Jeff, you bring up interesting points.\n\n""...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,26568,approved,0,0,0,1,0,0.0,0,4
299,240322,0.000000,I wonder how one can post an actual image? Mar...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,32846,approved,0,0,0,1,0,0.0,4,6
363,240417,0.000000,[Here's a relevant quote.](https://lh5.googleu...,0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,1,0,0.0,0,4
388,240447,0.000000,"Well, the easter egg in the penultimate senten...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,0,0,0.0,0,4
415,240485,0.000000,"While I agree with your conclusion, I think yo...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,32846,approved,0,0,0,0,0,0.0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1804501,6333342,0.000000,""" we're divided over issues, but people are di...",0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,399264,approved,0,0,0,0,0,0.0,10,4
1804710,6333658,0.000000,Falwell Jr. predicted that Moore would be vind...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,399518,approved,0,0,0,0,0,0.0,4,4
1804753,6333721,0.833333,I saved where I could because my children matt...,0.0,0.0,0.0,0.833333,0.0,NaN,NaN,...,399301,approved,0,0,0,0,0,0.0,0,6
1804868,6333965,0.000000,"cont....GBA: ""here's the summation of that ""l...",0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,399318,approved,0,0,0,0,0,0.0,0,4
1804873,6334010,0.000000,Students defined as EBD are legally just as di...,0.0,0.0,0.0,0.000000,0.0,NaN,NaN,...,399318,approved,0,0,0,0,0,0.0,0,4

In [11]:
js_test= jigsaw_test[~jigsaw_test['sentence'].str.contains('\[')]

TypeError: Invalid comparison between dtype=int64 and str

In [13]:
jigsaw_test[jigsaw_test['sentence'].str.contains('\[')]

            id                                           sentence
0      7097320  [ Integrity means that you pay your debts.]\n\...
113    7097433  "U.S. POSITION ON EAST JERUSALEM:\n\nOfficial ...
190    7097510  Reading the mans history on CNN-has 100% ZERO ...
358    7097678  A recent Ontario decision explained why employ...
416    7097736  [Actually, homicide is defined as "the deliber...
...        ...                                                ...
96330  7193650  Were you an advocate of science, you would com...
96413  7193733  Although that is a oft-used Talking Point [Pel...
96597  7193917  ["The administrator believes we should have pe...
96623  7193943  The Permanent Fund Earnings Reserve was not to...
97000  7194320  IRT "Leave parks natural, minus commercials". ...

[480 rows x 2 columns]

In [33]:
js_test.to_csv('value/data/GLUE/SST/js_test.csv')

In [8]:
js_test

            id                                           sentence
1      7097321  This is malfeasance by the Administrator and t...
2      7097322  @Rmiller101 - Spoken like a true elitist. But ...
3      7097323  Paul: Thank you for your kind words.  I do, in...
4      7097324  Sorry you missed high school. Eisenhower sent ...
5      7097325  Let’s see if I understand this; Berkowitz anno...
...        ...                                                ...
97315  7194635  He should lose his job for promoting mis-infor...
97316  7194636  "Thinning project is meant to lower fire dange...
97317  7194637  I hope you millennials are happy that you put ...
97318  7194638  I'm thinking Kellyanne Conway (a.k.a. The Trum...
97319  7194639  I still can't figure why a pizza in AK cost mo...

[96840 rows x 2 columns]